/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'apps-agents': RouteRecordInfo<'apps-agents', '/apps/Agents', Record<never, never>, Record<never, never>>,
    'apps-agents-add': RouteRecordInfo<'apps-agents-add', '/apps/Agents/add', Record<never, never>, Record<never, never>>,
    'apps-agents-edit': RouteRecordInfo<'apps-agents-edit', '/apps/Agents/edit', Record<never, never>, Record<never, never>>,
    'apps-agents-groups': RouteRecordInfo<'apps-agents-groups', '/apps/AgentsGroups', Record<never, never>, Record<never, never>>,
    'apps-attachments': RouteRecordInfo<'apps-attachments', '/apps/Attachments', Record<never, never>, Record<never, never>>,
    'apps-auto-responses': RouteRecordInfo<'apps-auto-responses', '/apps/AutoResponses', Record<never, never>, Record<never, never>>,
    'apps-backup': RouteRecordInfo<'apps-backup', '/apps/Backup', Record<never, never>, Record<never, never>>,
    'apps-calendars': RouteRecordInfo<'apps-calendars', '/apps/Calendars', Record<never, never>, Record<never, never>>,
    'apps-chat': RouteRecordInfo<'apps-chat', '/apps/chat', Record<never, never>, Record<never, never>>,
    'apps-customers': RouteRecordInfo<'apps-customers', '/apps/Customers', Record<never, never>, Record<never, never>>,
    'apps-customers-groups': RouteRecordInfo<'apps-customers-groups', '/apps/CustomersGroups', Record<never, never>, Record<never, never>>,
    'apps-customer-users': RouteRecordInfo<'apps-customer-users', '/apps/CustomerUsers', Record<never, never>, Record<never, never>>,
    'apps-email-addresses': RouteRecordInfo<'apps-email-addresses', '/apps/EmailAddresses', Record<never, never>, Record<never, never>>,
    'apps-greetings': RouteRecordInfo<'apps-greetings', '/apps/Greetings', Record<never, never>, Record<never, never>>,
    'apps-integrity-check': RouteRecordInfo<'apps-integrity-check', '/apps/IntegrityCheck', Record<never, never>, Record<never, never>>,
    'apps-kanban': RouteRecordInfo<'apps-kanban', '/apps/kanban', Record<never, never>, Record<never, never>>,
    'apps-knowledge-base': RouteRecordInfo<'apps-knowledge-base', '/apps/knowledge-base', Record<never, never>, Record<never, never>>,
    'apps-knowledge-base-add': RouteRecordInfo<'apps-knowledge-base-add', '/apps/knowledge-base/add', Record<never, never>, Record<never, never>>,
    'apps-knowledge-base-edit': RouteRecordInfo<'apps-knowledge-base-edit', '/apps/knowledge-base/edit', Record<never, never>, Record<never, never>>,
    'apps-organization-structure': RouteRecordInfo<'apps-organization-structure', '/apps/OrganizationStructure', Record<never, never>, Record<never, never>>,
    'apps-permissions': RouteRecordInfo<'apps-permissions', '/apps/permissions', Record<never, never>, Record<never, never>>,
    'apps-permissions': RouteRecordInfo<'apps-permissions', '/apps/Permissions', Record<never, never>, Record<never, never>>,
    'apps-post-master-mail-accounts': RouteRecordInfo<'apps-post-master-mail-accounts', '/apps/PostMasterMailAccounts', Record<never, never>, Record<never, never>>,
    'apps-post-master-mail-accounts-add': RouteRecordInfo<'apps-post-master-mail-accounts-add', '/apps/PostMasterMailAccounts/add', Record<never, never>, Record<never, never>>,
    'apps-post-master-mail-accounts-edit': RouteRecordInfo<'apps-post-master-mail-accounts-edit', '/apps/PostMasterMailAccounts/edit', Record<never, never>, Record<never, never>>,
    'apps-priorities': RouteRecordInfo<'apps-priorities', '/apps/Priorities', Record<never, never>, Record<never, never>>,
    'apps-queues': RouteRecordInfo<'apps-queues', '/apps/Queues', Record<never, never>, Record<never, never>>,
    'apps-queues-add-edit': RouteRecordInfo<'apps-queues-add-edit', '/apps/QueuesAddEdit', Record<never, never>, Record<never, never>>,
    'apps-roles-components-permission-tree-node': RouteRecordInfo<'apps-roles-components-permission-tree-node', '/apps/roles/components/PermissionTreeNode', Record<never, never>, Record<never, never>>,
    'apps-roles-components-role-extended-permissions': RouteRecordInfo<'apps-roles-components-role-extended-permissions', '/apps/roles/components/RoleExtendedPermissions', Record<never, never>, Record<never, never>>,
    'apps-roles-components-role-info-card': RouteRecordInfo<'apps-roles-components-role-info-card', '/apps/roles/components/RoleInfoCard', Record<never, never>, Record<never, never>>,
    'apps-roles-edit': RouteRecordInfo<'apps-roles-edit', '/apps/roles/edit', Record<never, never>, Record<never, never>>,
    'apps-roles': RouteRecordInfo<'apps-roles', '/apps/Roles', Record<never, never>, Record<never, never>>,
    'apps-services': RouteRecordInfo<'apps-services', '/apps/Services', Record<never, never>, Record<never, never>>,
    'apps-session-management': RouteRecordInfo<'apps-session-management', '/apps/SessionManagement', Record<never, never>, Record<never, never>>,
    'apps-settings-ticket-settings-system-configuration': RouteRecordInfo<'apps-settings-ticket-settings-system-configuration', '/apps/settings/ticket-settings/SystemConfiguration', Record<never, never>, Record<never, never>>,
    'apps-signatures': RouteRecordInfo<'apps-signatures', '/apps/Signatures', Record<never, never>, Record<never, never>>,
    'apps-sla': RouteRecordInfo<'apps-sla', '/apps/SLA', Record<never, never>, Record<never, never>>,
    'apps-states': RouteRecordInfo<'apps-states', '/apps/States', Record<never, never>, Record<never, never>>,
    'apps-system-log': RouteRecordInfo<'apps-system-log', '/apps/SystemLog', Record<never, never>, Record<never, never>>,
    'apps-template-queues': RouteRecordInfo<'apps-template-queues', '/apps/TemplateQueues', Record<never, never>, Record<never, never>>,
    'apps-templates': RouteRecordInfo<'apps-templates', '/apps/Templates', Record<never, never>, Record<never, never>>,
    'apps-tickets': RouteRecordInfo<'apps-tickets', '/apps/tickets', Record<never, never>, Record<never, never>>,
    'apps-tickets-add': RouteRecordInfo<'apps-tickets-add', '/apps/tickets/add', Record<never, never>, Record<never, never>>,
    'apps-tickets-edit': RouteRecordInfo<'apps-tickets-edit', '/apps/tickets/edit', Record<never, never>, Record<never, never>>,
    'apps-tickets-schedules': RouteRecordInfo<'apps-tickets-schedules', '/apps/tickets/Schedules', Record<never, never>, Record<never, never>>,
    'apps-tickets-view': RouteRecordInfo<'apps-tickets-view', '/apps/tickets/view', Record<never, never>, Record<never, never>>,
    'apps-type-categories': RouteRecordInfo<'apps-type-categories', '/apps/TypeCategories', Record<never, never>, Record<never, never>>,
    'apps-types': RouteRecordInfo<'apps-types', '/apps/Types', Record<never, never>, Record<never, never>>,
    'apps-workflows': RouteRecordInfo<'apps-workflows', '/apps/Workflows', Record<never, never>, Record<never, never>>,
    'dashboards-analytics': RouteRecordInfo<'dashboards-analytics', '/dashboards/analytics', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-account-settings-tab': RouteRecordInfo<'pages-account-settings-tab', '/pages/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
  }
}
