ALTER TABLE sla ADD COLUMN type VARCHAR(255);
ALTER TABLE sla ADD COLUMN solution_time INTEGER DEFAULT 0;
ALTER TABLE sla ADD COLUMN min_incident_time INTEGER DEFAULT 10;
ALTER TABLE sla ADD COLUMN response_notification INTEGER DEFAULT 20;
ALTER TABLE sla ADD COLUMN update_notification INTEGER DEFAULT 80;
ALTER TABLE sla ADD COLUMN solution_notification INTEGER DEFAULT 80;
