import BxTicket from '@core/components/icons/BxTicket.vue'

export default [
  { heading: 'Приложения' },
  
  {
    title: 'Почта',
    icon: { icon: 'bx-envelope' },
    to: 'apps-email',
  },
  {
    title: 'Чат',
    icon: { icon: 'bx-chat' },
    to: 'apps-chat',
  },
  {
    title: 'Календарь',
    icon: { icon: 'bx-calendar' },
    to: 'apps-calendar',
  },
  {
    title: 'Канбан',
    icon: { icon: 'bx-grid' },
    to: 'apps-kanban',
  },
  {
    title: 'Тикеты',
    icon: { icon: BxTicket },
    children: [
      { title: 'Список', to: 'apps-tickets' },
      { title: 'Создать', to: { path: '/apps/tickets/add' } },
    ],
  },
  {
    title: 'Пользователи',
    icon: { icon: 'bx-user' },
    children: [
      { title: 'Список', to: 'apps-user-list' },
      { title: 'Просмотр', to: { name: 'apps-user-view-id', params: { id: 21 } } },
    ],
  },
  {
    title: 'Роли и разрешения',
    icon: { icon: 'bx-check-shield' },
    children: [
      { title: 'Роли', to: 'apps-roles' },
      { title: 'Разрешения', to: 'apps-permissions' },
    ],
  },
  
  { heading: 'Настройки' },
  
  {
    title: 'Администрирование',
    icon: { icon: 'bx-cog' },
    children: [
      { title: 'Обзор', to: 'apps-settings-administration-administration-settings' },
      { title: 'Календари', to: 'apps-settings-administration-calendars' },
      { title: 'Общий каталог', to: 'apps-settings-administration-general-catalog' },
      { title: 'Менеджер пакетов', to: 'apps-settings-administration-package-manager' },
      { title: 'Журнал производительности', to: 'apps-settings-administration-performance-log' },
      { title: 'Управление сессиями', to: 'apps-settings-administration-session-management' },
      { title: 'SQL Box', to: 'apps-settings-administration-sql-box' },
      { title: 'Сбор данных поддержки', to: 'apps-settings-administration-support-data-collector' },
      { title: 'Системная конфигурация', to: 'apps-settings-administration-system-configuration' },
      { title: 'Поддержка системных файлов', to: 'apps-settings-administration-system-file-support' },
      { title: 'Системный журнал', to: 'apps-settings-administration-system-log' },
      { title: 'Системное обслуживание', to: 'apps-settings-administration-system-maintenance' },
      { title: 'Перевод', to: 'apps-settings-administration-translation' },
    ],
  },
  {
    title: 'Коммуникация',
    icon: { icon: 'bx-message' },
    children: [
      { title: 'Уведомления администратора', to: 'apps-settings-communication-notifications-admin-notification' },
      { title: 'Уведомления о встречах', to: 'apps-settings-communication-notifications-appointment-notifications' },
      { title: 'Журнал коммуникаций', to: 'apps-settings-communication-notifications-communication-log' },
      { title: 'Настройки уведомлений', to: 'apps-settings-communication-notifications-communication-notifications-settings' },
      { title: 'Адреса email', to: 'apps-settings-communication-notifications-email-addresses' },
      { title: 'OAuth2', to: 'apps-settings-communication-notifications-oauth2' },
      { title: 'PGP ключи', to: 'apps-settings-communication-notifications-pgp-keys' },
      { title: 'Post Master фильтры', to: 'apps-settings-communication-notifications-post-master-filters' },
      { title: 'Почтовые аккаунты', to: 'apps-settings-communication-notifications-post-master-mail-accounts' },
      { title: 'SMIME сертификаты', to: 'apps-settings-communication-notifications-smime-certificates' },
      { title: 'Уведомления заявок', to: 'apps-settings-communication-notifications-ticket-notifications' },
    ],
  },
  {
    title: 'Автоматизация',
    icon: { icon: 'bx-sync' },
    children: [
      { title: 'ACL', to: 'apps-settings-processes-automation-acl' },
      { title: 'Динамические поля', to: 'apps-settings-processes-automation-dynamic-fields' },
      { title: 'Экраны динамических полей', to: 'apps-settings-processes-automation-dynamic-fields-screens' },
      { title: 'Generic Agent', to: 'apps-settings-processes-automation-generic-agent' },
      { title: 'Настройки автоматизации', to: 'apps-settings-processes-automation-processes-automation-settings' },
      { title: 'Управление процессами', to: 'apps-settings-processes-automation-process-management' },
      { title: 'Связи атрибутов заявок', to: 'apps-settings-processes-automation-ticket-attribute-relations' },
      { title: 'Веб-сервисы', to: 'apps-settings-processes-automation-web-services' },
    ],
  },
  {
    title: 'Заявки (настройки)',
    icon: { icon: 'bx-detail' },
    children: [
      { title: 'Вложения', to: 'apps-settings-ticket-settings-attachments' },
      { title: 'Автоответы', to: 'apps-settings-ticket-settings-auto-responses' },
      { title: 'Приветствия', to: 'apps-settings-ticket-settings-greetings' },
      { title: 'Приоритеты', to: 'apps-settings-ticket-settings-priorities' },
      { title: 'Автоответы очереди', to: 'apps-settings-ticket-settings-queue-auto-response' },
      { title: 'Очереди', to: 'apps-settings-ticket-settings-queues' },
      { title: 'Услуги', to: 'apps-settings-ticket-settings-services' },
      { title: 'Подписи', to: 'apps-settings-ticket-settings-signatures' },
      { title: 'SLA', to: 'apps-settings-ticket-settings-sla' },
      { title: 'Статусы', to: 'apps-settings-ticket-settings-states' },
      { title: 'Вложения шаблонов', to: 'apps-settings-ticket-settings-template-attachments' },
      { title: 'Очереди шаблонов', to: 'apps-settings-ticket-settings-template-queues' },
      { title: 'Шаблоны', to: 'apps-settings-ticket-settings-templates' },
      { title: 'Типы', to: 'apps-settings-ticket-settings-types' },
      { title: 'Рабочие процессы', to: 'apps-settings-ticket-settings-workflows' },
    ],
  },
  {
    title: 'Пользователи и группы',
    icon: { icon: 'bx-group' },
    children: [
      { title: 'Агенты', to: 'apps-settings-users-groups-roles-agents' },
      { title: 'Группы агентов', to: 'apps-settings-users-groups-roles-agents-groups' },
      { title: 'Роли агентов', to: 'apps-settings-users-groups-roles-agents-roles' },
      { title: 'Компании', to: 'apps-settings-users-groups-roles-customers' },
      { title: 'Группы клиентов', to: 'apps-settings-users-groups-roles-customers-groups' },
      { title: 'Клиенты', to: 'apps-settings-users-groups-roles-customer-users' },
      { title: 'Клиенты компаний', to: 'apps-settings-users-groups-roles-customer-users-customers' },
      { title: 'Группы клиентов', to: 'apps-settings-users-groups-roles-customer-users-groups' },
      { title: 'Услуги клиентов', to: 'apps-settings-users-groups-roles-customer-users-services' },
      { title: 'Группы', to: 'apps-settings-users-groups-roles-groups' },
      { title: 'Роли', to: 'apps-settings-users-groups-roles-roles' },
      { title: 'Группы ролей', to: 'apps-settings-users-groups-roles-roles-groups' },
      { title: 'Настройки ролей', to: 'apps-settings-users-groups-roles-users-groups-roles-settings' },
    ],
  },
]
